name: Acceptance

on:
  workflow_run:
    workflows: [Release]
    types:
      - completed
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install jq
      run: |
        sudo apt-get update
        sudo apt-get install -y jq
    - name: Get latest journalfs
      run: |
        url=$(curl --silent "https://api.github.com/repos/awfulcooking/journalfs/releases/latest" | jq -r 'first(.assets[] | select(.name=="journalfs")) | .browser_download_url')
        wget $url
    - name: Get latest journalfs.service
      run: |
        url=$(curl --silent "https://api.github.com/repos/awfulcooking/journalfs/releases/latest" | jq -r 'first(.assets[] | select(.name=="journalfs")) | .browser_download_url')
        wget $url
    - name: Install it
      run: |
        chmod +x journalfs

        sudo install -m 755 journalfs /usr/bin/journalfs
        sudo install -m 755 journalfs /usr/lib/systemd/system/journalfs.service

        sudo useradd --system --user-group journalfs
        sudo useradd -aG journalfs $USER

        sudo mkdir /journal
        sudo chown journalfs:journalfs /journal

        sudo systemctl daemon-reload
        sudo systemctl enable --now journalfs.service
    - name: List /journal
      run: |
        sudo ls -1p /journal/
    - name: List /journal as non-root
      run: |
        ls -1p /journal/
      continue-on-error: true
    - name: Look for service/ and scope/
      run: |
        sudo ls -1p /journal/ | grep service
        sudo ls -1p /journal/ | grep scope
        echo "Success!"
