name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20

    - name: Checkout
      uses: actions/checkout@v2

    - name: Make
      run: make

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
      - name: journalfs
        path: ./journalfs
      - name: journalfs.service
        path: ./contrib/journalfs.service
